### ISSUE TITLE
Cannot install solution to DAWN instance

### ISSUE THREAD

**Issue by belkassaby** [Itema-as/eclipse-marketplace-server#109]
Hello Torkild,
I was about to put the marketplace into production, but I came across the same problem we had about a month ago when trying to install a solution to a running eclipse instance.
The version of DAWN I’m trying to install the solution to is here :http://opengda.org/DawnDiamond/2.1/downloads/builds-release/
When I try to install the solution through the market place client, there is no “install” button near the featured solution , and when I try to install it using the drag and drop, I have the following error that pops up
![mpc_error](https://cloud.githubusercontent.com/assets/1378819/16585334/3ce47e6e-42b8-11e6-8671-b25222aec482.png)
![mpc_noinstall](https://cloud.githubusercontent.com/assets/1378819/16585333/3ce1dc86-42b8-11e6-9130-f6c2f41ba8ca.png)

I thought that adding the feature identifier field in the solution sorted that problem. I tested that with the last version of the dawn-marketplace-server available.

Kind regards

baha

**Comment by turesheim** [comment]
The sample solution contains some metadata that the new Eclipse does not like. Creating a new solution and uploading this will work as expected.

**Comment by turesheim** [comment]
Looks good now. You may have to delete the database and start again, since the "created" field had a wrong value.

**Comment by belkassaby** [comment]
Great Thank you for your help! I've recreated a solution and it does work after cleaning up the database.
